[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
serde_yaml.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"
